version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb/lametric-ebay
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  db:
    image: mongo:4.2.1-bionic
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
